"""empty message

Revision ID: fa0dc055f43d
Revises: 
Create Date: 2020-01-21 12:58:26.131942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0dc055f43d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('pais', sa.String(length=80), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('probabilidade', sa.String(length=80), nullable=False),
    sa.Column('precipitacao', sa.String(length=80), nullable=False),
    sa.Column('min', sa.String(length=80), nullable=False),
    sa.Column('max', sa.String(length=80), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
